# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: myapp_development
  pool: 20
  encoding: utf8
  username: root
  password: root
  host:  localhost

test:
  adapter: mysql2
  database: myapp_test
  pool: 20
  encoding: utf8
  username: root
  password: root
  host:  localhost

production:
  adapter: mysql2
  database: myapp
  pool: 20
  encoding: utf8
  username: root
  password: root
  host:  localhost