# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e1a4992fe8a74933aebb8b6a9044166dbfc5522e4ffd9e2ebf321dc8f96eab1433bb7196aeef7673ea6f2d4267126b8c014eada913e9f6670c7faee19e880db

test:
  secret_key_base: d88e2791918899f7bd6b58a84745edd19b8ad944627d30b97fca2bb87c1c0a376ee0dd832259733c197a4e1ddd9e207a0ead7ad059e156cea23d2cd85877cb80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
